# .github/workflows/backend-ci.yml
name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/backend.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release backend/backend.sln

      - name: Run tests
        run: dotnet test backend/backend.sln --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish backend

      # Deployment to Azure is commented out for this mock project.
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'your-app-name'
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ./publish
